# Generated by Django 5.1.2 on 2024-10-31 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_financeiro', '0003_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='gestao_financeiro.grupo'),
        ),
    ]
