# Generated by Django 5.1.2 on 2024-11-02 03:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_financeiro', '0004_transacao_grupo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='codigo_acesso',
        ),
        migrations.AlterField(
            model_name='grupo',
            name='membros',
            field=models.ManyToManyField(related_name='grupos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
