# Generated by Django 5.1.2 on 2024-11-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_financeiro', '0005_remove_grupo_codigo_acesso_alter_grupo_membros_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='criador',
        ),
        migrations.AddField(
            model_name='grupo',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transacao',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateField(),
        ),
    ]
