# Generated by Django 5.1.2 on 2024-11-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_financeiro', '0006_remove_grupo_criador_grupo_descricao_transacao_saldo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='importado_ofx',
            field=models.BooleanField(default=False),
        ),
    ]
