# Generated by Django 5.1.2 on 2024-11-03 20:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_financeiro', '0008_remove_grupo_descricao_grupo_criador'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='chave_convite',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
